# This is a basic workflow to help you get started with Actions

name: Deploy to Salesforce  Org


# On Push to Master/Main this will be triggered.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: 14
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      run: npm install sfdx-cli --global

    # Authorize SF Org
    - name: Authorize SF Org
 
      run: sfdx force:auth:jwt:grant --clientid 3MVG9ojmGst1I5HO05Iq5HjeRyUEXzBJOUHtAhXyHRpIUK.54KZ1kJ6PekO31DjiwfDRsGtUM55gbCBljdIAG --jwtkeyfile  ./buildfiles/server.key  --username vnarayanaswamy@suyati.com.devops1 --instanceurl https://test.salesforce.com -a Dev1
      
          # Convert to Deploy Source
    - name: Convert to Deploy Source
      run: sfdx force:source:convert -r ./force-app -d ./toDeploy
    
    # Run Validation of Deploy Source
    - name: Run Validation on Deploy Source
      run: sfdx force:mdapi:deploy -c -d ./toDeploy -u Dev1
    
    # Deploy
    - name : Deploy to SF Org
      run: sfdx force:mdapi:deploy -d ./toDeploy -u Dev1 -w 10
